
#project 4
```{r}
# #combine dataset
# movie <- read.csv("~/Desktop/movie.csv")
# movie2 <- read.csv("~/Desktop/movie963_10000.csv")
# movie1 <- movie[1:963,]
# movie0_10000 <- rbind(movie1,movie2)
# movie3 <- read.csv("~/Desktop/movie10000_20000.csv")
# movie0_20000 <- rbind(movie0_10000,movie3)
# movie4 <- read.csv("~/Desktop/movie20000_33394.csv")
# movie0_33394 <- rbind(movie0_20000,movie4)
# write.csv(movie0_33394, file = "Desktop/old_movie.csv")

movie <- read.csv("~/Desktop/old_movie.csv")
dim(movie)

```

```{r}
#clean data
# movie$title <- as.character(movie$title)
# movie$title <- gsub("\\[.*","",movie$title) 
# movie$title <- gsub("\\(.*","",movie$title)
# movie$title <- gsub("\\~.*","",movie$title)
# movie$title <- gsub("\\{.*","",movie$title)
# movie$title <- gsub('[-]','',movie$title )
# write.csv(movie, file = "Desktop/movie_data.csv")
```

```{r}
# library(rvest)
# ASIN.inq="B001TK80AW"
# movie1<- read_html(paste("http://www.amazon.com/exec/obidos/ASIN/",ASIN.inq, sep=""))
# 
# movie1 %>% 
#   html_node("title") %>%
#   html_text()

devtools::install_github("hrbrmstr/omdbapi")
library(omdbapi)
library(devtools)
library(dplyr)
library(pbapply)

movie$Type <- "NA"
movie$Year <- "NA" 
movie$Director <- "NA"
movie$countries <- "NA"

n <- dim(movie)[1]

for(i in 1:n){
  print(i)
  tryCatch({
    title <- movie$title[i]
    movie$Type[i] <- get_genres(find_by_title(title))[1]
    movie$Year[i] <- unlist(find_by_title(title)[2],use.names = F)
    movie$Director[i] <- get_directors(find_by_title(title))
    movie$countries[i] <- get_countries(find_by_title(title))
  }, error=function(e){})
  }

# search_by_title("Spectacular SpiderMan")
# 
# #find type
# get_genres(find_by_title("Britney Spears"))[1]
# 
# #find directors
# get_directors(find_by_title("Super 8"))
# 
# #find countries
# get_countries(find_by_title("The Blind Swordsman: Zatoichi"))
```

```{r}
#write.csv(movie, file = "Desktop/movieset.csv")
# movie <- read.csv("~/Desktop/movieset.csv")
# movie2 <- movie[complete.cases(movie), ]
# str(movie2)
# saveRDS(movie2, file="~/data.Rds")
```

##pie chart
```{r}
library(plotly)
library(ggplot2)
library(dygraphs)
library(xts)
# movie <- movie[,c(2,4,6:9)]
# movie$Year <- gsub("\\–.*","",movie$Year))
# plot_ly(movie, x = Type, type = "histogram", color = Type)
# plot_ly(movie, x = countries, type = "histogram", color = countries)

summary <- sort(summary(movie$Director),decreasing = T)
A <- data.frame(Director = names(summary), number = summary)
rownames(A) <- NULL
A <- A[-c(1,2),]
A <- A[c(1:20),]
plot_ly(A, labels = Director, values = number, type = "pie") %>% 
  layout(title = "Top Director")

summary <- sort(summary(movie$Type),decreasing = T)
B <- data.frame(Type = names(summary), number = summary)
rownames(B) <- NULL
B <- B[c(1:15),]
plot_ly(B, labels = Type, values = number, type = "pie") %>% 
  layout(title = "Top Movie Type")
```

#timeline setup
```{r}
movie <- readRDS("~/Desktop/data.rds")

summary <- summary(as.factor(movie$Year));summary
ALL <- data.frame(year = names(summary), number = summary)
ALL <- ALL[-nrow(ALL),]
ALL$year <- as.Date(paste(ALL$year, "01", "01", sep=""), "%Y%m%d")
ALL$year <- as.POSIXlt(ALL$year)
ALL <- xts(ALL[,-1], order.by=ALL[,1])

#dygraph(ALL, main = "New Haven Temperatures", ylab = "Temp (F)")

summary <- summary(as.factor(movie$Year[movie$Type == "Action"]))
ACT <- data.frame(year = names(summary), number = summary)
ACT$year <- as.Date(paste(ACT$year, "01", "01", sep=""), "%Y%m%d")
ACT$year <- as.POSIXlt(ACT$year)
ACT <- xts(ACT[,-1], order.by=ACT[,1])
#dygraph(ACT, main = "New Haven Temperatures", ylab = "Temp (F)") %>% dyRangeSelector()

summary <- summary(as.factor(movie$Year[movie$Type == "Drama"]))
Drama <- data.frame(year = names(summary), number = summary)
Drama$year <- as.Date(paste(Drama$year, "01", "01", sep=""), "%Y%m%d")
Drama$year <- as.POSIXlt(Drama$year)
Drama <- xts(Drama[,-1], order.by=Drama[,1])
#dygraph(Drama, main = "New Haven Temperatures", ylab = "Temp (F)") %>% dyRangeSelector()

summary <- summary(as.factor(movie$Year[movie$Type == "Comedy"]))
Comedy <- data.frame(year = names(summary), number = summary)
Comedy$year <- as.Date(paste(Comedy$year, "01", "01", sep=""), "%Y%m%d")
Comedy$year <- as.POSIXlt(Comedy$year)
Comedy <- xts(Comedy[,-1], order.by=Comedy[,1])
#dygraph(Comedy, main = "New Haven Temperatures", ylab = "Temp (F)") %>% dyRangeSelector()

summary <- summary(as.factor(movie$Year[movie$Type == "Horror" | movie$Type == "Thriller"]))
Horror <- data.frame(year = names(summary), number = summary)
Horror$year <- as.Date(paste(Horror$year, "01", "01", sep=""), "%Y%m%d")
Horror$year <- as.POSIXlt(Horror$year)
Horror <- xts(Horror[,-1], order.by=Horror[,1])
#dygraph(Horror, main = "New Haven Temperatures", ylab = "Temp (F)") %>% dyRangeSelector()

summary <- summary(as.factor(movie$Year[movie$Type == "Crime"]))
Crime <- data.frame(year = names(summary), number = summary)
Crime$year <- as.Date(paste(Crime$year, "01", "01", sep=""), "%Y%m%d")
Crime$year <- as.POSIXlt(Crime$year)
Crime <- xts(Crime[,-1], order.by=Crime[,1])
#dygraph(Crime, main = "New Haven Temperatures", ylab = "Temp (F)") %>% dyRangeSelector()

summary <- summary(as.factor(movie$Year[movie$Type == "Animation"]))
Animation <- data.frame(year = names(summary), number = summary)
Animation$year <- as.Date(paste(Animation$year, "01", "01", sep=""), "%Y%m%d")
Animation$year <- as.POSIXlt(Animation$year)
Animation <- xts(Animation[,-1], order.by=Animation[,1])
#dygraph(Crime, main = "New Haven Temperatures", ylab = "Temp (F)") %>% dyRangeSelector()

TYPE <- cbind(ALL,Comedy,Animation,ACT,Drama,Horror,Crime)
colnames(TYPE) <- c("ALL","Comedy","Animation","Action","Drama","Horror&Thriller","Crime")
saveRDS(TYPE, file="~/Desktop/TYPE.Rds")
```

```{r}
search <- sort(summary(movie$Type[movie$Year =="2014"]),decreasing = T)
search <- data.frame(names = names(search), search)
rownames(search) <- NULL
search <- search[1:15,]
plot_ly(search, x = names, y = search, mode = "markers")
```

#clean score data
```{r}
#alldata <- read.csv("~/Desktop/data_50_10.csv")

#most popular movie
summary <- sort(table(alldata$product_productid),decreasing = T)
summary <- summary[1:100]
id <- data.frame(id_all = names(summary), summary = summary)

#best movie
summary <- sort(table(alldata$product_productid[alldata$review_score == 5]),decreasing = T)
summary <- summary[1:100]
id_5 <- data.frame(id_5 = names(summary), summary_5 = summary)

#worst movie
summary <- sort(table(alldata$product_productid[alldata$review_score == 1]),decreasing = T)
summary <- summary[1:100]
id_1 <- data.frame(id_1 = names(summary), summary_1 = summary)

#top reviwer
summary <- sort(table(alldata$review_userid),decreasing = T)
summary <- summary[1:100]
review <- data.frame(review = names(summary), n = summary)

score <- cbind(id,id_5,id_1,review)
rownames(score) <- NULL
score[,1] <- as.character(score[,1])
score[,3] <- as.character(score[,3])
score[,5] <- as.character(score[,5])
#saveRDS(score, file="~/Desktop/score.Rds")
#write.csv(score, file="score.csv")

score <- readRDS("~/Desktop/score.Rds")
#saveRDS(score2, file="~/Desktop/score.Rds")
score2 <- score2[,3:13]
plot_ly(score2, x = summary, y = name, mode = "markers")
```


```{r}
# alldata <- read.csv("~/Desktop/data_50_10.csv")
# movie <- read.csv("~/Desktop/old_movie.csv")
# movie <- movie[,c(4,6,7)]
# movie2 <- readRDS("~/Desktop/data.Rds")
# movie3 <- merge(movie2,movie,by = "product_productid", all.x=TRUE)
# movie3 <- movie3[,-2]
# 
# summary <- sort(table(alldata$product_productid),decreasing = T)
# ID <- data.frame(product_productid = names(summary), summary = summary)
# ID2 <- ID[!duplicated(ID$summary),]
# rownames(ID2) <- NULL
# M <- merge(ID2,movie3, by = "product_productid", all.x=TRUE)
# G <- M[order(M$summary,decreasing = T),]
# 
# Final <- G[complete.cases(G$Type), ]
# saveRDS(Final, file="~/Desktop/Final.Rds")

# Final <- readRDS("~/Desktop/Final.Rds")
# Final <- Final[1:100,]
# rownames(Final) <- NULL

score <- readRDS("~/Desktop/score.Rds")
# score <- score[,c(7,8)]
# score <- cbind(Final,score)
# score <- score[c(1:50),]
# saveRDS(score, file="~/Desktop/score.Rds")

Final <- readRDS("~/Desktop/Final.Rds")
plot_ly(Final, x = Type, y = summary, mode = "markers",color = summary)
plot_ly(Final, x = Type,  y = summary, type = "box")

movie <- readRDS("~/Desktop/data.rds")
```

```{r}
# alldata <- alldata[,2:7]
# final.data <- merge(alldata,Final,by = "product_productid")
# colnames(final.data)[7] <-"total_reviews"
# colnames(final.data)[12] <-"movie_name"
# write.csv(final.data,"~/Desktop/final.data.csv")
```

#Timeline 2
```{r}
movie_time <- read.csv("~/Desktop/movie_time.csv")
movie.time <- merge(movie_time,Final,by = "product_productid")
movie.time <- movie.time[,c(1,3,5,7,8,10,13)]
movie.time$newtime <- as.POSIXlt(movie.time$newtime)
movie.time$title.y <- as.character(movie.time$title.y)
movie.time$title.y <- gsub("\\[.*","",movie.time$title.y)
movie.time$title.y <- gsub("\\(.*","",movie.time$title.y)
movie.time$title.y <- gsub("\\~.*","",movie.time$title.y)
movie.time$title.y <- gsub("\\{.*","",movie.time$title.y)
movie.time$title.y <- gsub('[-]','',movie.time$title.y)
saveRDS(movie.time, file="~/Desktop/time.Rds")

#create timeline dataframe
sub <-  movie.time[movie.time$product_productid =="B000005PPB",]
sub <- sub[order(sub$newtime),]

mean <- c()

for (i in 1: dim(sub)[1]){
  
  mean[i] <- mean(sub[1:i,3])

}
mean

sub <- cbind(sub,mean)
data <- xts(sub[,-4], order.by = sub[,4])

#dygraph(data[,3], main = "Review Score Timeline ", ylab = "Score") %>% dyRangeSelector()

dygraph(data[,7], main = "Variation of Average Score", ylab = "Score") %>% dyRangeSelector() %>%  dyOptions(stackedGraph = TRUE)
```

